name: wrf_python_assimilation
channels:
  - defaults
  - conda-forge
dependencies:
  - python
  - numpy
  - setuptools
  - numpy
  - scipy
  - netcdf4
  - xarray
  - wrf-python
  - matplotlib
  - seaborn
  - pyyaml
  - tqdm
  - jupyter
  - ipykernel
  - pip


