cross_sections_job:
  paths:
    output: /home/jorge.gacitua/datosdemerzel/wrf_python_Assimilation/data/ensemble_cross_sections.npz
    template: /ABS/PATH/TO/001/wrfout_d01_YYYY-mm-dd_HH:MM:SS
    pattern:  /ABS/PATH/TO/{member}/wrfout_d01_YYYY-mm-dd_HH:MM:SS
  ensemble:
    mem_ini: 1
    mem_end: 30
    pad: 3
  variables: ["QGRAUP","QRAIN","QSNOW","temp","pressure"]
  cross_section:
    start: [-39.2, -65.5]
    end:   [-39.2, -62.0]
    timeidx: -1
