"""
src/naming.py
=============
The naming scheme, in one place, so the runner, the extractor and the migration cannot
drift apart.

    WS_{DATASET}_{mode}_{HHMM}_LOC{L}[_{FLAGS}]
    3D_subsets_{DATASET}/subset_{DATASET}_{YYYYMMDDHHMMSS}.npz

DATASET  A | B | C | D
mode     sweep | multiobs | point      (the runner's single_obs is `point`)
HHMM     1800 | 1900 | 2000 | 2100
L        the isotropic localization scale in km, as it appears in the config

Flags, combinable, in this order:

    QC<code> departure-band rejection active  (`qc.dep_band` is set)
    WIN     subset cut to the analysis window
    STEPS   intermediate tempering steps stored
    REF     reflectivity metric fields only   (`output.store_ref_fields`)
    FULL    state metric fields too           (`output.store_state_fields`)
    ALLMEM  every truth member, not just tm=0
    AS<x>   tempering slope other than the default

No field flag means light mode: per-domain scalars only.

The QC flag carries a code, because a run with a band and a run without one otherwise
collide on disk under the same name:

    QC        the band is set but unnamed          (legacy spelling, still accepted)
    QC2t8     reject 2 <= dep_b <= 8 dBZ
    QCm1t3    reject -1 <= dep_b <= 3 dBZ          (`m` is the minus sign)

The code is generated by `qc_code(band)` and cross-checked against `qc.dep_band`, so a
tag claiming QC2t8 on a config with a different band fails at startup.

ALLMEM and AS<x> are an extension to the five documented flags. They are here because
the runs on disk need them: without ALLMEM, `WS_D_sweep_1800_LOC0.1` and its all-member
sibling are one name, and they are different runs -- different stride, different
tempering ladder, different truth-member set. L is likewise not restricted to the
documented {0.1, 2.0}; L = 4 km runs exist and are cited in the published tables.

The point of validating here rather than at write time: a run that takes six hours
should not discover at the end that its name is wrong. `validate_experiment_tag` is
called from the runner's `main()` before any data is loaded.

A tag that disagrees with its own config is worse than an ugly one, because it is
believed. So every field is checked against the config rather than trusted:

    LOC        == sweep.loc_x (and loc_y, loc_z -- the tag claims isotropy)
    mode       == sweep.obs_points.mode
    QC flag    present exactly when qc.dep_band is set, and its code matches the band
    REF/FULL   match the output block's field switches
    ALLMEM     present exactly when the run covers more than one truth member
"""

import re

DATASETS = ("A", "B", "C", "D")
MODES = ("sweep", "multiobs", "point")
HOURS = ("1800", "1900", "2000", "2100")
BASE_FLAGS = ("QC", "WIN", "STEPS", "REF", "FULL")
FIELD_FLAGS = ("REF", "FULL")
FLAG_ORDER = ("QC", "WIN", "STEPS", "REF", "FULL", "ALLMEM")

STORAGE_LEVELS = ("light", "ref", "full")
STORAGE_FLAG = {"light": None, "ref": "REF", "full": "FULL"}

# The runner's internal mode names, and the token each becomes in a tag.
MODE_OF_TAG = {"sweep": "sweep", "multiobs": "multi_obs", "point": "single_obs"}
TAG_OF_MODE = {v: k for k, v in MODE_OF_TAG.items()}

TAG_RE = re.compile(
    r"^WS_(?P<ds>[ABCD])_(?P<mode>sweep|multiobs|point)_"
    r"(?P<hhmm>\d{4})_LOC(?P<loc>[\d.]+)"
    r"(?P<flags>(_(QC[m\d.t]*|WIN|STEPS|REF|FULL|ALLMEM|AS[\d.]+))*)$"
)

SUBSET_RE = re.compile(
    r"^3D_subsets_(?P<ds>[ABCD])/subset_(?P=ds)_(?P<stamp>\d{14})\.npz$"
)

EXPECTED = (
    "WS_{A|B|C|D}_{sweep|multiobs|point}_{HHMM}_LOC{L}[_FLAGS]\n"
    "  flags, in this order: QC WIN STEPS REF FULL ALLMEM AS<x>\n"
    "  e.g. WS_D_sweep_1900_LOC0.1_ALLMEM\n"
    "       WS_C_multiobs_2100_LOC2.0_FULL"
)


class TagError(ValueError):
    """The tag is malformed, or it disagrees with the config it belongs to."""


def parse_tag(tag):
    """Split a tag into its fields. Raises TagError if it does not match."""
    m = TAG_RE.match(tag or "")
    if m is None:
        raise TagError(f"experiment_tag {tag!r} does not match the scheme.\n"
                       f"expected:\n  {EXPECTED}")
    flags = [f for f in m.group("flags").split("_") if f]
    return dict(dataset=m.group("ds"), mode=m.group("mode"), hhmm=m.group("hhmm"),
                loc=float(m.group("loc")), loc_str=m.group("loc"), flags=flags)


def _scalar(val, name):
    """A sweep parameter that must name exactly one value.

    loc_x/loc_y/loc_z are a Cartesian product in _build_combos, so a config listing
    two scales produces combos at both and no single LOC in the tag can be true of
    them. One config per scale; the tag is what makes that visible.
    """
    if isinstance(val, dict):
        raise TagError(f"sweep.{name} is a range; a tag names one localization. "
                       f"Use one config per scale.")
    if isinstance(val, (list, tuple)):
        if len(val) != 1:
            raise TagError(
                f"sweep.{name} lists {len(val)} values {list(val)}. loc_x/loc_y/loc_z "
                f"are a Cartesian product, so this run would cover several "
                f"localizations and no single LOC in the tag is true of it. "
                f"Use one config per scale.")
        return float(val[0])
    return float(val)


def truth_member_count(cfg):
    """How many truth members the config covers, for the ALLMEM check."""
    tm = (cfg.get("sweep") or {}).get("truth_members", 0)
    if isinstance(tm, dict):
        step = int(tm.get("step", 1)) or 1
        return len(range(int(tm["start"]), int(tm["stop"]) + 1, step))
    if isinstance(tm, (list, tuple)):
        return len(tm)
    return 1


# The output block. Four independent switches over what reaches disk, plus three over
# the intermediate tempering steps. They are independent because their costs differ by
# orders of magnitude: on dataset A a multi_obs scheme file is ~80 MB of reflectivity
# fields, ~590 MB of state fields and ~2.9 GB of ensemble, against a few kB of scalars.
OUTPUT_DEFAULTS = {
    "store_scalars":      True,    # always; domain aggregates only, a few kB
    "store_ref_fields":   False,   # 13 (nx,ny,nz) reflectivity fields
    "store_state_fields": False,   # 12 (nx,ny,nz,nvar) state fields
    "store_ensemble":     False,   # xf/xa/truth_state -- what store_fields used to mean
    "steps_departure":    False,   # departure VECTOR per tempering step, float32
    "steps_cells":        (),      # [[i,j,k], ...] full ensemble at these cells, per step
    "steps_fields":       False,   # full metric fields per step. Expensive; rarely wanted
}

OUTPUT_FIELD_KEYS = ("store_ref_fields", "store_state_fields")

# What `store_fields: true` used to mean, kept so old configs still reproduce.
STORE_FIELDS_ALIAS = ("store_ref_fields", "store_state_fields", "store_ensemble")


def _as_bool(val, key):
    if isinstance(val, bool):
        return val
    raise TagError(f"output.{key} must be true or false, got {val!r}")


def output_levels_of(cfg, warn=None):
    """Resolve the `output` block, the deprecated `store_fields`, and `storage_level`.

    Returns a dict with every key in OUTPUT_DEFAULTS filled in.

    Three spellings can reach this function and they must not be mixed, because they
    disagree about the same bytes:

      output:          the current one, four independent switches
      storage_level:   light | ref | full -- the metric FIELDS only, ensemble separate
      store_fields:    deprecated; one switch meaning ref + state + ensemble

    With none of them set, the defaults are what the code has always done: multi_obs
    wrote every metric field and no ensemble, sweep and single_obs wrote scalar rows.
    Configs written before any of these keys existed therefore still reproduce, and
    validating them against that default does not retro-fail them.
    """
    out = dict(OUTPUT_DEFAULTS)
    block = cfg.get("output")
    legacy_level = cfg.get("storage_level")
    legacy_fields = cfg.get("store_fields")

    if block is not None and (legacy_level is not None or legacy_fields is not None):
        raise TagError(
            "config sets `output:` together with the deprecated "
            f"{'storage_level' if legacy_level is not None else 'store_fields'}. "
            "They describe the same bytes and can disagree. Keep `output:` and delete "
            "the other.")

    if block is not None:
        if not isinstance(block, dict):
            raise TagError(f"`output` must be a mapping, got {type(block).__name__}")
        unknown = set(block) - set(OUTPUT_DEFAULTS)
        if unknown:
            raise TagError(f"unknown output keys {sorted(unknown)}; "
                           f"expected any of {sorted(OUTPUT_DEFAULTS)}")
        for k, v in block.items():
            if k == "steps_cells":
                out[k] = tuple(tuple(int(q) for q in c) for c in (v or ()))
                if any(len(c) != 3 for c in out[k]):
                    raise TagError("output.steps_cells entries must be [i, j, k] triples")
            else:
                out[k] = _as_bool(v, k)
    else:
        # No `output` block: fall back to the historical defaults for this mode, then
        # let the deprecated keys override them.
        if obs_mode_of(cfg) == "multi_obs":
            out["store_ref_fields"] = True
            out["store_state_fields"] = True
        if legacy_level is not None:
            lvl = str(legacy_level).lower()
            if lvl not in STORAGE_LEVELS:
                raise TagError(f"storage_level {lvl!r} is not one of {STORAGE_LEVELS}")
            out["store_ref_fields"] = lvl in ("ref", "full")
            out["store_state_fields"] = lvl == "full"
        if legacy_fields is not None:
            if _as_bool(legacy_fields, "store_fields") :
                for k in STORE_FIELDS_ALIAS:
                    out[k] = True
                if warn is not None:
                    warn("`store_fields: true` is deprecated. It means "
                         "store_ref_fields + store_state_fields + store_ensemble; "
                         "write those under `output:` instead.")
            elif warn is not None:
                warn("`store_fields: false` is deprecated and had no effect on the "
                     "metric fields; write `output:` instead.")

    if not out["store_scalars"]:
        raise TagError(
            "output.store_scalars: false would write a file with nothing in it -- the "
            "domain scalars are the one thing every storage level keeps. Drop the run "
            "instead of the scalars.")
    return out


def storage_level_of(cfg):
    """The metric-FIELD level implied by the output block: light | ref | full.

    Kept as the single word the tag's REF/FULL flag is checked against, and the word
    `compute_multi_obs_metrics` takes. The ensemble switch is deliberately outside it:
    `store_ensemble` is orthogonal to which metric fields are kept.
    """
    o = output_levels_of(cfg)
    if o["store_state_fields"]:
        return "full"
    return "ref" if o["store_ref_fields"] else "light"


def obs_mode_of(cfg):
    """The runner's mode name, with the tag's spelling accepted as a synonym.

    `point` is what a tag calls single_obs, and §6's point mode is configured with
    that word, so both spellings resolve here rather than in three call sites.
    """
    obs = (cfg.get("sweep") or {}).get("obs_points", "sweep")
    mode = obs if isinstance(obs, str) else obs.get("mode", "sweep")
    return MODE_OF_TAG.get(mode, mode)


def dep_band_of(cfg):
    """The departure-rejection band, or None.

    `qc.departure_band` is refused rather than aliased. It named a RETENTION rule --
    keep the points inside the band -- and `dep_band` is a REJECTION rule on the same
    numbers, so the same two numbers under the old key would silently mean the
    opposite observation set.
    """
    qc = cfg.get("qc") or {}
    if "departure_band" in qc:
        raise TagError(
            "qc.departure_band was RETENTION (keep observations inside the band); "
            "qc.dep_band is REJECTION (drop them). The same two numbers mean the "
            "opposite observation set, so the key is not aliased. Rename it to "
            "`dep_band` once you have checked which one you meant.")
    band = qc.get("dep_band")
    if band is None:
        return None
    try:
        lo, hi = float(band[0]), float(band[1])
    except (TypeError, IndexError, ValueError):
        raise TagError(f"qc.dep_band must be [lo, hi] in dBZ, got {band!r}")
    if lo > hi:
        raise TagError(f"qc.dep_band {band} has lo > hi")
    return (lo, hi)


def has_dep_band(cfg):
    return dep_band_of(cfg) is not None


def _num_token(x):
    """A number as a filename token: minus becomes `m`, the point survives, `.0` goes."""
    s = f"{float(x):g}"
    return s.replace("-", "m")


def qc_code(band):
    """The QC flag for a band: `QC2t8` for [2, 8], `QCm1t3` for [-1, 3].

    Without a code, a run with a band and a run without one collide on disk under one
    name, and so do two runs with different bands.
    """
    if band is None:
        return None
    lo, hi = band
    return f"QC{_num_token(lo)}t{_num_token(hi)}"


def validate_experiment_tag(cfg, tag=None):
    """Check a tag against its own config. Returns the parsed fields.

    Raises TagError with what is wrong and what was expected. Called at startup, not
    at write time.
    """
    tag = tag if tag is not None else cfg.get("experiment_tag")
    p = parse_tag(tag)
    problems = []

    sweep = cfg.get("sweep") or {}
    try:
        lx = _scalar(sweep.get("loc_x", 10.0), "loc_x")
        ly = _scalar(sweep.get("loc_y", 10.0), "loc_y")
        lz = _scalar(sweep.get("loc_z", 4.0), "loc_z")
        if not (lx == ly == lz):
            problems.append(f"the tag says LOC{p['loc_str']}, which claims an isotropic "
                            f"scale, but the config has loc_x={lx}, loc_y={ly}, loc_z={lz}")
        elif lx != p["loc"]:
            problems.append(f"the tag says LOC{p['loc_str']} but sweep.loc_x is {lx}")
    except TagError as e:
        problems.append(str(e))

    mode = obs_mode_of(cfg)
    if MODE_OF_TAG[p["mode"]] != mode:
        problems.append(f"the tag says mode {p['mode']!r} but "
                        f"sweep.obs_points.mode is {mode!r} "
                        f"(expected {TAG_OF_MODE.get(mode, '?')!r})")

    qc_got = [f for f in p["flags"] if f.startswith("QC")]
    try:
        band = dep_band_of(cfg)
    except TagError as e:
        band = None
        problems.append(str(e))
    want_qc = qc_code(band)
    if len(qc_got) > 1:
        problems.append(f"the tag carries {qc_got}; there is one departure band")
    elif qc_got and band is None:
        problems.append(f"the tag carries {qc_got[0]} but qc.dep_band is not set, so no "
                        f"departure-band rejection would happen")
    elif band is not None and not qc_got:
        problems.append(f"qc.dep_band is {list(band)} but the tag does not carry "
                        f"{want_qc}")
    elif qc_got and band is not None and qc_got[0] not in ("QC", want_qc):
        # Bare `QC` is the legacy spelling and stays legal: it claims a band without
        # naming it, which is ambiguous on disk but not wrong.
        problems.append(f"the tag carries {qc_got[0]} but qc.dep_band is {list(band)} "
                        f"(expected {want_qc})")

    o = None
    try:
        o = output_levels_of(cfg)
        lvl = storage_level_of(cfg)
    except TagError as e:
        lvl = None
        problems.append(str(e))
    if lvl is not None:
        want = STORAGE_FLAG[lvl]
        got = [f for f in p["flags"] if f in FIELD_FLAGS]
        if len(got) > 1:
            problems.append(f"the tag carries {got}; REF and FULL are mutually exclusive")
        elif want is None and got:
            problems.append(f"the tag carries {got[0]} but no metric fields are stored "
                            f"(per-domain scalars only)")
        elif want is not None and not got:
            problems.append(f"the output block stores {lvl!r} metric fields so the tag "
                            f"must carry {want}")
        elif want is not None and got and got[0] != want:
            problems.append(f"the tag carries {got[0]} but the output block stores "
                            f"{lvl!r} metric fields (expected {want})")

    if o is not None:
        steps = o["steps_departure"] or o["steps_fields"] or bool(o["steps_cells"])
        if "STEPS" in p["flags"] and not steps:
            problems.append("the tag carries STEPS but no output.steps_* switch is on")
        if steps and "STEPS" not in p["flags"]:
            problems.append("output.steps_* is on but the tag does not carry STEPS")

    # ALLMEM is deliberately NOT cross-checked. sweep.truth_members is only a fallback
    # for when --tm is absent, and the all-member runs are campaigns of 60 one-member
    # jobs that each write into the same directory. So a single invocation cannot know
    # how many members the run will end up covering, and checking it against the config
    # fails legitimate runs: WS_D_sweep_1800_LOC0.1 carries truth_members 0..59 and
    # produced tm00 only. The flag is legal, ordered, and left to the author.

    order = [("QC" if f.startswith("QC") else f)
             for f in p["flags"] if f.startswith("QC") or f in FLAG_ORDER]
    if order != sorted(order, key=FLAG_ORDER.index):
        problems.append(f"flags {p['flags']} are out of order; the order is "
                        f"{' '.join(FLAG_ORDER)} then AS<x>")

    if problems:
        raise TagError(
            f"experiment_tag {tag!r} disagrees with its config:\n" +
            "".join(f"  - {q}\n" for q in problems) +
            f"expected form:\n  {EXPECTED}")
    return p


def validate_subset_path(path, dataset_id):
    """Check a subset output path against the scheme and the config's dataset_id."""
    import os
    norm = "/".join(os.path.normpath(path).split(os.sep)[-2:])
    m = SUBSET_RE.match(norm)
    if m is None:
        raise TagError(
            f"subset output {path!r} does not match the scheme.\n"
            f"expected a path ending in:\n"
            f"  3D_subsets_{{A|B|C|D}}/subset_{{same letter}}_{{YYYYMMDDHHMMSS}}.npz\n"
            f"  e.g. .../data/3D_subsets_D/subset_D_20240319190000.npz")
    if dataset_id is None:
        raise TagError(
            "cross_sections_job.dataset_id is required. It is written into every "
            "subset as `dataset_id`; it is NOT parsed back out of the filename, so "
            "that a mistyped path fails instead of silently relabelling the data.")
    if m.group("ds") != dataset_id:
        raise TagError(f"the output path says dataset {m.group('ds')} but "
                       f"cross_sections_job.dataset_id is {dataset_id!r}")
    return m.group("ds"), m.group("stamp")
